#!/bin/bash
#v.2 | Testing phase
GREEN="\e[1;32m"
RED="\e[1;31m"
YELLOW="\e[1;33m"
BLUE="\e[1;34m"
MAGENTA="\e[1;35m"
CYAN="\e[1;36m"
WHITE="\e[1;37m"
COEND="\e[0m"

            #description "Keep my very important program running"

            #start on desktop-session-start
            #stop on desktop-shutdown

            #respawn

            #script
            #    /path/to/my/very/important/program
            #end script

INTERNET = wget -q --tries=10 --timeout=20 --spider http://google.com
if [[ $? -eq 0 ]]; then
        echo "Connected"                  #Virtually a ping to google, thus bringing back an answer
else
        echo "Disconnected"
fi

UPTIME = uptime

USERS = w

DISKUSAGE = df -H

DSPACE = df -H | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{ print $5 " " $1 }'

OSNAME = cat /etc/issue.net           #uname -o

KERNEL = uname -a       #uname -r

OSV = lsb_release -a            #uname -v | Potential command to describe all the OS related area's?

HOST = if [ "$HOSTNAME" = host ]; then
    printf '%s\n' "on the right host"                   #EDIT
else
    printf '%s\n' "uh-oh, not on host"
fi

IIP = /sbin/ifconfig eth0 | greo "inet addr" | awk -F: '{print $2}' | awk '{print $1}'

EIP = curl http://ipecho.net/plain; echo

NAMESERVER = cat /etc/resolv.conf

RAMUSAGE = free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%)\n", $3,$2,$3*100/$2 }'
df -h | awk '$NF=="/"{printf "Disk Usage: %d/%dGB (%s)\n", $3,$2,$5}'
top -bn1 | grep load | awk '{printf "CPU Load: %.2f\n", $(NF-2)}'

LOADAVERAGE = uptime                            #'man uptime' Should be researched

ARC = echo ARCH=`uname -m`

OSTYPE = uname -s

SWAPUSAGE = free [-g|-k|-m]          #Check the man page if not working. | http://www.unix.com/man-page/linux/1/free/

start()
{

}

menu()
{
	clear
	echo "   ----------------------------------- "
	echo -e "$BLUE Internet: $INTERNET $COEND"
	echo -e "$BLUE Operating System Type : $OSTYPE $COEND"
	echo -e "$BLUE OS Name : $OSNAME $COEND"
	echo -e "$BLUE OS Version : $OSV $COEND"
	echo -e "$BLUE Architecture : $ARC $COEND"
	echo -e "$BLUE Kernel Release : $KERNEL $COEND"
	echo "   ----------------------------------- "
	echo -e "$BLUE Hostname : $HOST $COEND"
	echo -e "$BLUE Internal IP : $IIP $COEND"
	echo -e "$BLUE External IP : $EIP $COEND"
	echo -e "$BLUE Name Servers : $NAMESERVER $COEND"
	echo "   ----------------------------------- "
	echo -e "$BLUE Logged In Users : $USERS $COEND"
	echo -e "$BLUE Ram Usages : $RAMUSAGE $COEND"
	echo -e "$BLUE Swap Usages : $SWAPUSAGE $COEND"
	echo -e "$BLUE Disk Usages : $DISKUSAGE $COEND"
	echo -e "$BLUE Disk Space : $DSPACE $COEND"
	echo "   ----------------------------------- "
	echo -e "$BLUE Load Average : $LOADAVERAGE $COEND"
	echo -e "$BLUE System Uptime Days/(HH:MM) : $UPTIME $COEND"
	echo -e "$RED [1] Exit $COEND"
	echo -e "$GREEN ----------------------------------- $COEND"
	read START_MENU

	case $START_MENU in
	1)
		echo -e "$RED [!] Closing script $COEND"
		sleep 1
		clear
		
		;;

	*)
		echo -e $RED [!] Invalid Input $COEND"
		sleep 1
		clear
		menu
		;;

	esac
}

menu
