#!/bin/bash
#Simplified Aircrack
#V2
airmon-ng start wlan0

start()
{
echo "Start"

}

menu()
{
	
clear
echo "-------------------------------------------------------"
echo -e "\e[1;32m ~Wireless Network Tool~ \e[0m"
printf "Which operation would you like to run...?\n"
echo -e "\e[1;32m [1] Start \e[0m"
echo -e "\e[1;31m [2] Exit \e[0m"
echo "-------------------------------------------------------"
date
uptime
read start_menu

case $start_menu in
1)
	echo -e "\e[1;32m Moving to main menu... \e[0m"
	clear
	start
	
	;;
	
2)
	echo -e "\e[1;32m Shutting Down... \e[0m"
	clear
	exit
	
	;;
	
*)
	echo -e "\e[1;31m Invalid Input, Redirecting... \e[0m"
	sleep 1
	menu
	;;
	esac
}

menu

begin()
{
echo -e "\e[1;33m Loading Menu... \e[0m"

}
menu2()
{
	
clear
echo -e "\e[1;33m ############################################### \e[0m"
printf "[1] View all surrounding wireless networks\n"
printf "[2] View all users connected to a specific network\n"
printf "[3] Sniffing IVs\n"
echo -e "\e[1;31m [4] Exit \e[0m"
echo -e "\e[1;32m ----------------------------------------------------------- \e[0m"
read begin_menu2

case $begin_menu2 in
1)
	sleep 1
	if [ $? -eq 0 ]; then
	    echo -e "\e[1;32m [+] Success... \e[0m"
	else
	    echo -e "\e[1;31m [!] Unsuccessful... \e[0m"
	fi
	sleep 1
	airmon-ng start wlan0
	airodump-ng mon0
	clear
	menu2
	
	;;
	
2)
	sleep 1
	if [ $? -eq 0 ]; then
	    echo -e "\e[1;32m [+] Success... \e[0m"
	else
	    echo -e "\e[1;31m [!] Unsuccessful... \e[0m"
	fi
	sleep 1
	airmon-ng start wlan0
	echo -e "\e[1;31m [!] Input BSSID \e[0m"
	read BSSID
	echo -e "\e[1;31m [!] Input WLAN0... \e[0m"
	read WLAN
	airodump-ng -c 11 --bssid $BSSID -w dump $WLAN
	clear
	menu2
	
	;;
	
3)
	sleep 1
	if [ $? -eq 0 ]; then
	 echo -e "\e[1;32m [+] You will listen on one CH... \e[0m"
	else
    	echo -e "\e[1;31m [!] Unsuccessful... \e[0m"
	fi
	sleep 1
	echo -e "\e[1;32m Input BSSID... \e[0m"
	read BSSID
	airodump-ng -c 11 --bssid $BSSID -w dump mon0
	echo -e "\e[1;32m Data written | Sniff complete \e[0m"
	clear
	menu2
	
	;;
	
4)
	echo -e "\e[1;31m [!] Shutting down... \e[0m"
	clear
	exit
	
	;;
	
*)
	echo -e "\e[1;31m Invalid Input, Redirecting... \e[0m"
	clear
	menu2
	;;
	esac
}

menu2
