#!/bin/bash
#Simplified Aircrack | Use ROOT
#V3
GREEN="\e[1;32m"
RED="\e[1;31m"
YELLOW="\e[1;33m"
COEND="\e[0m"

start()
{
echo "Start"

}

menu()
{

clear
echo "-------------------------------------------------------"
echo -e "$GREEN ~Simplified Aircrack~ $COEND"
printf "Which operation would you like to run...?\n"
echo -e "$GREEN [1] Start $COEND"
echo -e "$RED [2] Exit $COEND"
echo "-------------------------------------------------------"
date
uptime
read start_menu

case $start_menu in
1)
	echo -e "$GREEN Moving to main menu... $COEND"
	clear
	start

	;;

2)
	echo -e "$RED Shutting Down... $COEND"
	clear
	exit

	;;

*)
	echo -e "$RED Invalid Input, Redirecting... $COEND"
	sleep 1
	menu
	;;
	esac
}

menu

begin()
{
echo -e "$GREEN Loading Menu... $COEND"

}
menu2()
{

clear
echo -e "$YELLOW ############################################### $COEND"
printf "[1] View all surrounding wireless networks\n"
printf "[2] View all users connected to a specific network\n"
printf "[3] Sniffing IVs\n"
echo -e "$RED [4] Exit $COEND"
echo -e "$GREEN ----------------------------------------------------------- $COEND"
read begin_menu2
case $begin_menu2 in
1)
	sleep 1
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	sleep 1
	airmon-ng start wlan0
	airodump-ng mon0
	clear
	menu2

	;;

2)
	sleep 1
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	sleep 1
	airmon-ng start wlan0
	echo -e "$RED [!] Input BSSID $COEND"
	read BSSID
	echo -e "$RED [!] Input WLAN0... $COEND"
	read WLAN
	airodump-ng -c 11 --bssid $BSSID -w dump $WLAN
	clear
	menu2

	;;

3)
	sleep 1
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] You will listen on one CH... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	sleep 1
	echo -e "$GREEN Input BSSID... $COEND"
	read BSSID
	airodump-ng -c 11 --bssid $BSSID -w dump mon0
	echo -e "$GREEN Data written | Sniff complete $COEND"
	clear
	menu2

	;;

4)
	echo -e "$RED [!] Shutting down... $COEND"
	clear
	exit

	;;

*)
	echo -e "$RED [!] Invalid Input, Redirecting... $COEND"
	clear
	menu2
	;;
	esac
}

menu2
