#!/bin/bash

#v0.1

#Disabling the guest account
sudo gedit /etc/lightdm/lightdm.conf #Brings you to the lightdm txt area
#allow-guest=false to disable account


#Updates
sudo apt-get update && sudo apt-get dist-upgrade

#Firewall 
sudo enable ufw
sudo ufw allow 22
sudo ufw allow 80

#Services
echo "Welcome to the services section" #Choose wether to disable certain services or overpass skip over them and keep them
echo "1. Disable telnet?"
echo "2. Keep telnet?"
read IDEA
echo

if [[ $IDEA == 1 ]]; then 
  sudo service rm telnet
elif [[ $IDEA == 2 ]]; then
  echo "Continue operation..."

# New feature remove root SSH login
# blah blah pretend this is the code that does that
if [[ 1 -eq 2 ]]; then   # This is never true so it will never be executed
    echo "blah"
    echo "blah"
    echo "blah"
    echo "blah"
fi
