#!/bin/bash

#v0.5

#Change insecure root password
#su #Un-note later

#Limit root access
#cat /etc/groups
#sudo gedit /etc/groups #DEBATING ON IF TO KEEP OR REMOVE
#Remove unnecessary users from admin group

#Disable SSH root login if not supposed to be enabled
sudo gedit /etc/ssh/sshd_config #Change line permitrootlogin "yes" to no
echo "Press any key to continue..."
read IDEA
echo

#Audit Policies #DEBATING ON IF TO KEEP OR REMOVE
#sudo apt-get install auditd
#sudo auditctl -e 1
#sudo gedit /etc/audit/auditd.conf

#Disabling the guest account
sudo gedit /etc/lightdm/lightdm.conf #Brings you to the lightdm txt area
#allow-guest=false to disable account and THEN greeter-hide-users=true

#Password for all non-administrators
#sudo passwd  #Put username of user after "passwd" , UN-NOTE THESE WITH USERS FOR COMPETITION
#sudo passwd
#sudo passwd
#sudo passwd
#sudo passwd
#sudo passwd
#sudo passwd
#sudo passwd
#sudo passwd
#sudo passwd 

#Install OpenSSH
#Sudo apt-get install OpenSSH-server #Un-note these to process through the script

#Shadow passwords and groups
sudo gedit /etc/group
echo "Continue..."
read IDEA
echo

sudo gedit /etc/shadow
echo "Continue..."
read IDEA
echo

#Minimum password age
sudo gedit /etc/login.defs #Max days, 150. Min days, 10. Pass_Warn_Age, 7.

#Password Policy
sudo gedit /etc/pam.d/common-password #ENTER AT THE END OF THE COMPETITION
#At end of file, " auth required pam_tally2.so deny =10 onerr=failunlock_time=1800


#Updates
sudo apt-get update && sudo apt-get dist-upgrade

#Firewall 
sudo ufw enable
sudo ufw allow 22
sudo ufw allow 80
sudo ufw default deny

#Services
echo "Running services on this computer" #List's all services running

sudo service --status-all

echo "Continue to common service removal section..." #Choose wether to keep or disable telnet and apache2
read IDEA
echo

echo "1. Disable telnet?"
echo "2. Keep telnet?"
read IDEA
echo

if [[ $IDEA == 1 ]]; then
  sudo service telnet stop 
  sudo service rm telnet
elif [[ $IDEA == 2 ]]; then
  echo "Continue operation..."
read IDEA
echo

echo "1. Disable apache2?"
echo "2. Keep apache2?"
read IDEA
echo

if [[ $IDEA == 1 ]]; then
  sudo service apache2 stop
  sudo service rm apache2
elif [[ $IDEA == 2 ]]; then
  echo "Continue operation..."
read IDEA
echo

#Backdoor checking
sudo netstat -tulpna
echo "Continue..." #Pause time to check the backdoors then to move down script
read IDEA
echo

sudo grep -r 'nc' /*
echo "Continue Operation..."
read IDEA
echo

sudo gedit /etc/cron*
echo "Continue Operation..."
read IDEA
echo

#Files with prohibited Extensions
#sudo find / -name "*" #Un-note this later
#sudo find / -name "*"
#sudo find / -name "*"
#sudo find / -name "*"
#sudo find / -name "*"
