#!/bin/bash

#RUN THIS SCRIPT AS SUDO "sudo bash <script> for example
#v0.8

start()
{
	echo "Starting Program..."
	
}

menu()
{

	clear
		printf "~CYBER SECURITY TOOL~\n"
		printf "Which operation would you like to run...?\n"
		echo "[1] Start"
		echo "[2] Exit"
		echo "[3] ReadMe"
		read start_menu
	
	
		case $start_menu in
		1)
			echo "Starting Program..."
			sleep 1
			clear
			start
		
			;;
	
		2)
			echo "Shutting down..."
			sleep 1
			clear
			exit
		
			;;
	
		3)
			clear
			printf "This is made up of my older script, but put into a selection so you have options as-"
			printf "To what you want to do.\n"
			read WAIT_FOR_USER
			menu
		
			;;
		
		*)
			echo "Invalid Input, Redirecting..."
			sleep 1
			menu
			;;
		
		esac
}

menu

echo "Loading Selection..."

begin()
{
		echo "Loading Menu..."
}

menu2()
{

	printf "########################################################\n"
	printf "[1] Prohibited Media File Searcher\n"
	printf "[2] Updater\n"
	printf "[3] SSH Root Login\n"
	printf "[4] Insecure Root Passwd\n"
	printf "[5] System Logs\n"
	printf "[6] User Checking\n"
	printf "[7] Group Checking\n"
	printf "[8] Service Checker\n"
	printf "[9] Password Policy\n"
	printf "[10] Account Policy\n"
	printf "[11] Exit\n"
	echo "----------------------------------------------------------"
	read begin_menu2


		case $begin_menu2 in
		1)
		echo "Searching for Media Files..."
		echo "------------------------------------------------------------"
		find / -name "*.mp3"
		find / -name "*.wma"
		find / -name "*.mp4"
		find / -name "*.mov"
		find / -name "*.avi"
		find / -name "*.gif"
		find / -name "*.jpg"
		find / -name "*.jpeg"
		find / -name "*.png"
		find / -name "*.bmp"
		find / -name "*.exe"
	
		read SEARCH_RESULTS
		clear
		menu2
		
		;;
		
	2)
		echo "Updating..."
		apt-get update && apt-get dist-upgrade
		echo "UPDATED!"
		read WAIT_FOR_USER
		clear
		menu2
		
		;;
		
	3)
		echo "Permitting Root Login to NO."
		sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
		read WAIT_FOR_USER
		clear
		menu2
		
		;;
		
	4)
		echo "Fix Insecure Root Passwd"
		passwd
		read WAIT_FOR_USER
		clear
		menu2
		
		;;
		
	5)
		echo "Installing System Logs Checker..."
		apt-get install gnome
		gnome-system-logs
		read WAIT_FOR_USER
		clear
		menu2
		
		;;
		
	6)
		echo "Check Users..."
		cat /etc/passwd
		read WAIT_FOR_USER
		clear
		menu2
	
		;;
		
	7)
		echo "Check Groups..."
		cat /etc/group
		read WAIT_FOR_USER
		clear
		menu2
		
		;;
		
	8)
		echo "Checking Services..."
		service --status-all
		read WAIT_FOR_USER
		clear
		menu2
		
		;;
		
	9)
		echo "Password Policy Section"
		gedit /etc/pam.d/login.defs
		read WAIT_FOR_USER
		clear
		menu2
		
		;;
		
	10)
		echo "Account Policy Section"
		gedit /etc/pam.d/common-password
		clear
		read WAIT_FOR_USER
		clear
		menu2
		
		;;
		
	11)
		echo "Shutting down..."
		sleep 1
		clear
		exit
		
		;;
		
	*)
		echo "Invalid Input, Redirecting..."
		sleep 1
		clear
		menu2
		;;
	
	esac
}

menu2
