#!/bin/bash

#v0.7 Whole re-write of the script but cleaner

#System logs
apt-get install gnome
gnome-system-logs

#Change insecure root passwd
#sudo passwd root

#Limit Root Access
gedit /etc/group
read Continue
echo

gedit /etc/passwd
read Continue
echo

gedit /etc/shadow
read Continue
echo

#Sudoers file
sudo visudo
printf "Continue...\n\n"
read Continue
echo

#Running processes on the image
ps -A #Shows the processes
printf "Continue...\n\n"
read Continue
echo

#Disable SSH root login automatically
sudo gedit /etc/ssh/sshd_config
#Every yes it to be substitued with no

#Audit Policies
apt-get install auditd
auditctl -e 1
gedit /etc/audit/auditd.conf
printf "Continue...\n\n"

#Disabling the guest account as well as hiding users from login prompt
#gedit /etc/lightdm/lightdm.conf #For Ubuntu 12
#cd /usr/share/lightdm/lightdm.conf.d #For Ubuntu 14
#gedit 50-ubuntu.conf

#Password change for non-administrators
#sudo passwd <user>
#sudo passwd <user>
#sudo passwd <user>
#sudo passwd <user>
#sudo passwd <user>
#sudo passwd <user>
#sudo passwd <user>
#sudo passwd <user>
#sudo passwd <user>

#Minimum password age existing
gedit /etc/pam.d/login.defs
printf "Continue...\n\n"
read Continue
echo

#Account lockout policy
gedit /etc/pam.d/common-password
#auth-required pam_tally.so deny=5 onerr=failunlock_time=1800 #DO NOT UN-NOTE
printf "Continue...\n\n"

#System Update
apt-get update && apt-get dist-upgrade

#Firewall
ufw enable
ufw default deny

#Files with prohibited extensions
find / -name "*.mp3"
find / -name "*.wav"
find / -name "*.wma"
find / -name "*.mp4"
find / -name "*.mov"
find / -name "*.avi"
find / -name "*.gif"
find / -name "*.jpg"
find / -name "*.png"
find / -name "*.exe"
echo "Continue..."
read Continue
echo
