#!/bin/bash

# This functiion is created to prompt the user for what they need to be done
# if the user needs SSH they can say so and then have the function ran, otherwise
# if not needed the if statements are skipped over.

services(){
  
  ### SSH SECURITY ###
  echo "Does this image require SSH?"
  read ANSWER

  if [ ANSWER == 'yes' ]; then
    echo "SSH is required, calling SSH function"
  else
    echo "SSH is not required, skipping."
  fi
  
  ### SAMBA SECURITY ###
  echo "Does this image require samba?"
  read ANSWER

  if [ ANSWER == 'yes' ]; then
    samba
  else
    echo "Moving on..."
  fi
  
  ### APACHE / PHP SECURITY ###
  echo "Does this image require a webserver 'APACHE/PHP'?"
  read ANSWER

  if [ ANSWER == 'yes' ]; then
    apache
    php
  else
    echo "Moving on..."
  fi
  
  ### MYSQL SECURITY ###
  echo "Does this image require a database 'MYSQL'?"
  read ANSWER

  if [ ANSWER == 'yes' ]; then
    mysql
  else
    echo "Moving on..."
  fi
}
