#!/bin/bash
#RUN THIS SCRIPT AS SUDO, SOME FUNCTIONS REQUIRE SUDO.
#v11
GREEN="/e[1;32m"
YELLOW="/e[1;33m"
RED="/e[1;31m"
COEND="/e[0m"

start()
{
echo "Starting Program..."

}

menu()
{

clear
echo "-------------------------------------------------------"
echo -e "\e[1;32m ~CYBER SECURITY TOOL~ \e[0m"
printf "Which operation would you like to run...?\n"
echo -e "$GREEN [1] Start $COEND"
echo -e "$RED [2] Exit $COEND"
echo "-------------------------------------------------------"
date
uptime
read start_menu

case $start_menu in
1)
	echo -e "\$YELLOW Starting SECTOOL... $COEND"
	clear
	start

	;;

2)
	echo -e "$RED [!] Shutting down... $COEND"
	clear
	exit

	;;

*)
	echo -e "$RED Invalid Input, Redirecting... $COEND"
	sleep 1
	menu
	;;
	esac
}

menu

mkdir SECTOOLTXT

begin()
{
echo -e "\e[1;33m Loading Menu... \e[0m"

}

menu2()
{
clear                                                                                    #If something is done, skip over it
echo -e "$YELLOW ########################################################### $COEND"
printf "[1] Prohibited Media File Finder\n"
printf "[2] Updater\n"
printf "[3] SSH Root Login\n"
printf "[4] Insecure Root Passwd\n"
printf "[5] System Logs\n"
printf "[6] User Copy\n"
printf "[7] Group Copy\n"
printf "[8] Service Section\n"
printf "[9] Password Policy\n"
printf "[10] Account Policy\n"
printf "[11] Guest Account 12.04\n"
printf "[12] Guest Account 14.01\n"
printf "[13] RkHunter\n"
printf "[14] Executable Setup\n"
printf "[15] Basic Ping\n"
printf "[16] Firewall\n"
printf "[17] Listening Ports\n"
printf "[18] Visudo\n"
printf "[19] Crontab\n"
printf "[20] Procceses\n"
echo -e "$RED [21] Exit $COEND"
echo -e "$GREEN ----------------------------------------------------------- $COEND"
read begin_menu2

case $begin_menu2 in
1)
	echo -e "$YELLOW Presenting all media files with possible prohibited extensions $COEND"
	echo "------------------------------------------------------------"
	find / -name "*.mp3"
	find / -name "*.wma"
	find / -name "*.mp4"
	find / -name "*.mov"
	find / -name "*.avi"
	find / -name "*.gif"
	find / -name "*.jpg"
	find / -name "*.jpeg"
	find / -name "*.png"
	find / -name "*.bmp"
	find / -name "*.exe"
	if [ $? -eq 0 ]; then
	    echo -e "$GREEN [+] Success... $COEND"
	else
        echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read SEARCH_RESULTS
	clear
	menu2
	
	;;
	
2)
	echo -e "$YELLOW Updating... $COEND"
	apt-get update && apt-get dist-upgrade
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
3)
	echo -e "$RED [!] Permitting Root Login to NO. $COEND"
	sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
	if [ $? -eq ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccesful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
4)
	echo -e "$YELLOW Input New Root Passwd $COEND"
	passwd
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccesful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
5)
	echo -e "$YELLOW Installing Gnome System Log Viewer $COEND"
	apt-get install gnome
	gnome-system-logs
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+} Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
6)
	echo -e "$YELLOW Writing Users to -SECTOOLTXT- $COEND"
	cp /etc/passwd SECTOOLTXT
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
7)
	echo -e "$YELLOW Writing groups to -SECTOOLTXT- $COEND"
	cp /etc/group SECTOOLTXT
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
8)
	echo -e "$YELLOW Presenting Services $COEND"
	service --status-all
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful...$COEND"
	fi
	read WAIT_FOR_USER
	sleep 1
	clear
	menu3
	
	;;
	
9)
	echo -e "$YELLOW Password Policy Section $COEND"
	gedit /etc/pam.d/login.defs
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
10)
	echo -e "$YELLOW Account Policy Section $COEND"
	gedit /etc/pam.d/common-password
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
11)
	echo -e "$YELLOW Guest Account 12.04 $COEND"
	gedit /etc/lightdm/lightdm.conf #allow-guest= false | greeter-hide-users= true
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
12)
	echo -e "$YELLOW Guest Account 14.04 $COEND"
	cd /usr/share/lightdm/lightdm.conf.d/ #allow-guest= false | greeter-hide-users= true
	gedit 50-ubuntu.conf
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
13)
	echo -e "$RED [!] Beginning RkHunter Installation... $COEND"
	apt-get install chkrootkit
	apt-get install rkhunter
	rhkunter --update
	clear
	sleep 1
	rkhunter -c #SCANS FOR VULNERABILITIES
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read VIEW_MATERIAL
	clear
	menu2
	
	;;
	
14)
	echo -e "$RED [!] Setting Executable From All Directories... $COEND"
	sleep 1
	chmod +x SECTOOL
	cp SECTOOL /usr/bin/SECTOOL
	cp SECTOOL /usr/local/bin
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
		clear
		menu2
	fi
	echo -e "$GREEN ~You are now able to type <SECTOOL>in any directory to recall this tool~ $COEND"
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
15)
	echo -e "$YELLOW Enter an IP address or domain... $COEND"
	echo "------------------------------------------------------------"
	read INPUT
	ping $INPUT
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
16)
	clear
	menu4
	
	;;
	
17)
	netstat -tulpn
	if [ $? -eq 0 ]; then
		echo -e "$GREEN Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
18)
	visudo
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessfu... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
19)
	crontab -e
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
20)
	echo "Demonstration of process layout"
	ps
	ps -A
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu2
	
	;;
	
21)
	echo -e "$RED [!] Shutting down... $COEND"
	sleep 1
	clear
	exit
	
	;;
	
*)
	echo -e "$RED [!] Invalid Input, Redirecting... $COEND"
	sleep 1
	clear
	menu2
	;;
	esac
}

menu2

test()
{
echo "Starting Selection..."

}

menu3()
{
clear
echo -e "$YELLOW #########~Would you like to remove any services...?~################### $COEND"
printf "[1] Remove Telnet\n"
printf "[2] Remove Apache\n"
printf "[3] Remove OpenSSH\n"
printf "[4] Remove VSTFPD\n"
printf "[5] Application Menu\n"
echo -e "$GREEN ----------------------------------------------------------- $COEND"
read test_menu3

case $test_menu3 in
1)
	echo -e "$RED [!] Removing Telnet... $COEND"
	service rm telnet
	sleep 1
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu3
	
	;;
	
2)
	echo -e "$RED [!] Removing Apache... $COEND"
	service apache stop
	service rm apache2
	sleep 1
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu3
	
	;;
	
3)
	echo -e "$RED [!] Removing OpenSSH... $COEND"
	service ssh stop
	service rm ssh
	sleep 1
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu3
	
	;;
	
4)
	echo -e "$RED [!] Removing VSFTPD... $COEND"
	service vsftpd stop
	service rm vsftpd
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu3
	
	;;
	
5)
	echo -e "$YELLOW Proceeding to Menu... $COEND"
	sleep 1
	clear
	menu2
	
	;;
	
*)
	echo -e "$RED [!] Invalid Input, Redirecting... $COEND"
	sleep 1
	clear
	menu3
	;;
	esac
}

menu3

ubuntu()
{
	echo "Ubuntu Firewall"

}

menu4()
{
clear
echo -e "$YELLOW #########~Ubuntu OS Firewall Options...?~################### $COEND"
echo -e "$RED [!] This will only work with the Ubuntu OS [!] $COEND"
echo "-----------------------------------------------------------"
printf "[1] Enable Firewall\n"
printf "[2] Disable Firewall\n"
printf "[3] Firewall Status\n"
printf "[4] Allow port 22\n"
printf "[5] Allow port 80\n"
printf "[6] Default Firewall (RESET)\n"
printf "[7] Application Menu\n"
echo -e "$GREEN ---------------------------------------------------------- $COEND"
read ubuntu_menu4
	
case $ubuntu_menu4 in
1)
	ufw enable
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu4

	;;

2)
	ufw disable
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu4

	;;

3)
	ufw status
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu4
	
	;;
	
4)
	ufw allow 22
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessful... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu4
	
	;;
	
5)
	ufw allow 80
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsuccessfu... $COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu4
	
	;;
	
6)
	ufw default deny
	if [ $? -eq 0 ]; then
		echo -e "$GREEN [+] Success... $COEND"
	else
		echo -e "$RED [!] Unsucwcessful... \$COEND"
	fi
	read WAIT_FOR_USER
	clear
	menu4
	
	;;
	
7)
	echo -e "$YELLOW Moving back to main menu... $COEND"
	sleep 1
	clear
	menu2
	
	;;
	
*)
	echo -e "$RED [!] Invalid Input, Redirecting... $COEND"
	sleep 1
	clear
	menu4
	;;
	
esac
}
	
menu4
